#!/usr/bin/env bash
# generate-seatbelt.sh — Generate a macOS Seatbelt (.sb) profile
#
# Translates the profile configuration into a sandbox-exec compatible
# Seatbelt policy file. Called by macos-sandbox.sh.
#
# Usage:
#   generate-seatbelt.sh --port PORT --output FILE --workspace DIR
#
# Reads profile arrays from environment variables:
#   _CS_READ_ONLY_PATHS, _CS_BLOCKED_PATHS, _CS_WRITABLE_PATHS

set -euo pipefail

PROXY_PORT=""
OUTPUT=""
WORKSPACE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)      PROXY_PORT="$2"; shift 2 ;;
    --output)    OUTPUT="$2"; shift 2 ;;
    --workspace) WORKSPACE="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$PROXY_PORT" || -z "$OUTPUT" ]]; then
  echo "Usage: generate-seatbelt.sh --port PORT --output FILE --workspace DIR" >&2
  exit 1
fi

# Read arrays
readarray -t READ_ONLY_PATHS <<< "${_CS_READ_ONLY_PATHS:-}"
readarray -t BLOCKED_PATHS   <<< "${_CS_BLOCKED_PATHS:-}"
readarray -t WRITABLE_PATHS  <<< "${_CS_WRITABLE_PATHS:-}"

# Resolve macOS temp dir
DARWIN_TEMP="$(getconf DARWIN_USER_TEMP_DIR 2>/dev/null || echo '/tmp')"

cat > "$OUTPUT" <<HEADER
(version 1)
;;
;; Claude Sandbox — Seatbelt Profile
;; Generated by generate-seatbelt.sh
;;
;; Strategy: allow default → deny network → deny file-write → poke holes.
;; This is less strict than deny-default but far more compatible with the
;; many system paths that Node.js and Claude Code need to function on macOS.
;;

;; ── Base policy ──────────────────────────────────────────────
(allow default)
(deny network*)
(deny file-write*)

;; ── Network: proxy only ──────────────────────────────────────
;; All outbound traffic MUST go through our egress proxy.
;; Seatbelt cannot do domain-level filtering (only IP/port),
;; so the proxy handles domain allowlisting.
(allow network-outbound
  (remote tcp "localhost:${PROXY_PORT}"))
(allow network* (local tcp))

;; ── System writes needed by Node.js / Claude Code ────────────
(allow file-write*
  (subpath "/private/tmp")
  (subpath "/private/var/folders")
  (subpath "${DARWIN_TEMP}")
  (subpath "${HOME}/.npm")
  (subpath "${HOME}/.claude")
  (subpath "${HOME}/.config/claude")
  (subpath "${HOME}/.cache")
  (literal "${HOME}/.claude.json")
  (regex #"${HOME}/\\.claude\\.json\\.tmp.*")
)

HEADER

# ── Profile: writable paths ──────────────────────────────────
{
  echo ";; ── Profile: writable paths ──"
  for path in "${WRITABLE_PATHS[@]}"; do
    [[ -z "$path" ]] && continue
    mkdir -p "$path" 2>/dev/null || true
    abs_path="$(cd "$path" 2>/dev/null && pwd || echo "$path")"
    echo "(allow file-write* (subpath \"$abs_path\"))"
  done
  if [[ -n "$WORKSPACE" ]]; then
    mkdir -p "$WORKSPACE" 2>/dev/null || true
    ws_abs="$(cd "$WORKSPACE" && pwd)"
    echo "(allow file-write* (subpath \"$ws_abs\"))"
  fi
  echo ""
} >> "$OUTPUT"

# ── Profile: blocked paths (deny reads) ──────────────────────
{
  echo ";; ── Profile: blocked paths (deny reads) ──"
  echo ";; These override the (allow default) for reads."
  for path in "${BLOCKED_PATHS[@]}"; do
    [[ -z "$path" ]] && continue
    if [[ -e "$path" ]]; then
      abs_path="$(cd "$(dirname "$path")" 2>/dev/null && pwd)/$(basename "$path")"
      echo "(deny file-read* (subpath \"$abs_path\"))"
    fi
  done
  echo ""
} >> "$OUTPUT"

# ── Note about read-only paths ────────────────────────────────
{
  echo ";; ── Note: read-only paths ──"
  echo ";; On macOS with (allow default), read access is granted everywhere"
  echo ";; except blocked paths above. The read_only list from config.toml"
  echo ";; documents INTENT but does not need explicit Seatbelt rules."
  echo ";; Write access is already denied by (deny file-write*) above,"
  echo ";; so all non-writable paths are effectively read-only."
  for path in "${READ_ONLY_PATHS[@]}"; do
    [[ -z "$path" ]] && continue
    echo ";; read-only: $path"
  done
} >> "$OUTPUT"
